-- Generated by nwg-displays on 2026-08-03 at 23:08:48. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-3",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-1",
    default = true
})
