# https://www.simplethread.com/the-tmux-intro-i-wish-i-had-gotten/
# https://ianthehenry.com/posts/how-to-configure-tmux/

# No tmux bindings were harmed during the making of this config, except prefix-l and prefix-n

set -g prefix M-a
set -g prefix2 á
set -g mode-keys vi
set -g display-time 4000
set -g mouse on
set -g detach-on-destroy off
set -g status-position top
set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind n new-session

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Alt-<x> -> Select window x
bind -T root -N "Select window 1" M-1 select-window -t 1
bind -T root -N "Select window 2" M-2 select-window -t 2
bind -T root -N "Select window 3" M-3 select-window -t 3
bind -T root -N "Select window 4" M-4 select-window -t 4
bind -T root -N "Select window 5" M-5 select-window -t 5
bind -T root -N "Select window 6" M-6 select-window -t 6
bind -T root -N "Select window 7" M-7 select-window -t 7
bind -T root -N "Select window 8" M-8 select-window -t 8
bind -T root -N "Select window 9" M-9 select-window -t 9

# Alt-<hjkl> -> Navigate between panes, without jumping around screen edges
bind -T root -N "Select left pane"  M-h if -F "#{pane_at_left}"   "" "select-pane -L"
bind -T root -N "Select down pane"  M-j if -F "#{pane_at_bottom}" "" "select-pane -D"
bind -T root -N "Select up pane"    M-k if -F "#{pane_at_top}"    "" "select-pane -U"
bind -T root -N "Select right pane" M-l if -F "#{pane_at_right}"  "" "select-pane -R"

# Prefix-hjkl -> Create pane
bind h split-window -hb -c "#{pane_current_path}"
bind j split-window -v  -c "#{pane_current_path}"
bind k split-window -vb -c "#{pane_current_path}"
bind l split-window -h  -c "#{pane_current_path}"

# Prefix-HJKL -> Create pane (fullwidth)
bind H split-window -fhb -c "#{pane_current_path}"
bind J split-window -fv  -c "#{pane_current_path}"
bind K split-window -fvb -c "#{pane_current_path}"
bind L split-window -fh  -c "#{pane_current_path}"

# TokyoNight Storm theme (https://github.com/folke/tokyonight.nvim/blob/main/extras/tmux/tokyonight_storm.tmux)
source ~/.config/tmux/tokyonight_storm.tmux

# Support undercurls (see https://github.com/folke/tokyonight.nvim#:~:text=Fix%20undercurls%20in%20Tmux)
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g @open-S 'http://127.0.0.1:4433/?q='
